server:
  port: 8003
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lunjingjie/spring-cloud-demo
          search-paths: config-repo
          username: lunjingjie
          password: Ljj86328429
  rabbitmq:
      host: 127.0.0.1
      port: 5672
      username: guest
      password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

management:
  security:
     enabled: false